version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: yosseuf
      POSTGRES_PASSWORD: Zxcvb123er
      POSTGRES_DB: backend
    ports:
      - "5000:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
