spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/backend
    username: yosseuf
    password: Zxcvb123er
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true